version: '3'
services:
  posts-postgres:
    image: postgres:latest
    container_name: posts-postgres
    environment:
      - POSTGRES_DB=postsdb
      - POSTGRES_USER=posts
      - POSTGRES_PASSWORD=postspwd
    volumes:
      - posts-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  posts-api:
    build: ./posts-api
    container_name: posts-api
    environment:
      - DB_SERVER=posts-postgres
      - POSTGRES_DB=postsdb
      - POSTGRES_USER=posts
      - POSTGRES_PASSWORD=postspwd
    ports:
      - '8080:8080'
    depends_on:
      - posts-postgres

  posts-angular:
    build: ./posts-angular
    container_name: posts-angular
    ports:
      - '4200:80'
    depends_on:
      - posts-api

volumes:
  posts-db:
