CREATE TABLE public.post (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id integer NOT NULL,
	body varchar(255) not null,
	title varchar(255) not null,
	CONSTRAINT post_pk PRIMARY KEY (id)
);